name: trade_analytics
version: '1.0.0'
config-version: 2

profile: trade_analytics

model-paths: ["models"]
test-paths: ["tests"]

vars:
  hhi_coverage_tolerance: 0.005
  raw_start_date: '2023-01-01'
  raw_end_date: '2100-01-01'
  month_spine_start_date: '2023-01-01'
  month_spine_end_date: '2024-12-01'

seed-paths: ["seeds"]
